// export const state = {
//     api: process.env.VUE_APP_TAWHIRI_API_URL + "/predictor/predict_hourly",
//     markerPos: [37.4263, 138.8195],
//     prediction: [],
//     landing_line: [],
//     showPaths: [],
//     used_model: "",
//     datasets: ["latest", "timestamp"],
//     form_inputs: {
//         items: ["Kofu", "Chuchill"],
//         selectDataset: "latest",
//         months: [
//             { key: "Jan", value: 1 },
//             { key: "Feb", value: 2 },
//             { key: "Mar", value: 3 },
//             { key: "Apr", value: 4 },
//             { key: "May", value: 5 },
//             { key: "Jun", value: 6 },
//             { key: "Jul", value: 7 },
//             { key: "Aug", value: 8 },
//             { key: "Sep", value: 9 },
//             { key: "Oct", value: 10 },
//             { key: "Nov", value: 11 },
//             { key: "Dec", value: 12 },
//         ],
//         selectDay: "27",
//         selectMonth: 11,
//         selectYear: "2021",
//         selectHours: "10",
//         selectMinutes: "00",
//         numberOfHours: 24,
//         launchsite: "Kofu",
//         lat: 37.4263,
//         lng: 138.8195,
//         launchAttitude: 300,
//         burstAttitude: 30600,
//         ascentRate: 6.3,
//         descentRate: 4.13,
//     },
// };

