# Stage 0, "build-stage", based on Node.js, to build and compile the frontend
FROM node:lts-alpine
WORKDIR /app

COPY package.json /app/

RUN npm install

# COPY ./ /app/

ARG FRONTEND_ENV=development

ENV VUE_APP_ENV=${FRONTEND_ENV}

EXPOSE 8080
CMD [ "npm", "run" ,"serve" ]
# Stage 1, based on Nginx, to have only the compiled app, ready for production with Nginx
# FROM nginx:1.15

# COPY --from=build-stage /app/dist/ /usr/share/nginx/html

# COPY --from=build-stage /nginx.conf /etc/nginx/conf.d/default.conf
# COPY ./nginx-backend-not-found.conf /etc/nginx/extra-conf.d/backend-not-found.conf
