version: "3"

services:
    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile.dev
            args:
                - http_proxy=$http_proxy
                - https_proxy=$https_proxy
        env_file:
            - .env
        container_name: cusf_predictor_frontend
        # depends_on: 
        #     - backend
        ports:
            - "8080:8080"
        volumes:
            - ./frontend:/app
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile.dev
        ports:
            - "8000:8000"
        volumes:
            - ./backend/app:/app
            - /Users/cheesiang_leow/sel_program/tawhiri-datasets:/srv/tawhiri-datasets/
            - /Users/cheesiang_leow/sel_program/ruaumoko-dataset:/srv/ruaumoko-dataset/
        depends_on:
            - db
        env_file:
            - .env
    db:
        image: postgres:12
        volumes:
        - ./app-db-data:/var/lib/postgresql/data/pgdata
        env_file:
            - .env
        environment:
        - PGDATA=/var/lib/postgresql/data/pgdata
        ports:
            - "5432:5432"
    pgadmin:
        container_name: pgadmin4_container
        image: dpage/pgadmin4
        env_file:
            - .env
        depends_on: 
            - db
        environment:
            PGADMIN_LISTEN_PORT: ${PGADMIN_LISTEN_PORT}
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
        ports:
            - "${PGADMIN_LISTEN_PORT}:${PGADMIN_LISTEN_PORT}"
        restart: always
    tawhiri_sel:
        build:
            context: ./tawhiri_sel
            args:
                - http_proxy=$http_proxy
                - https_proxy=$https_proxy
        env_file: 
            - .env
        container_name: tawhiri_app
        ports:
            - "5000:5000"
        volumes:
            - /Users/cheesiang_leow/sel_program/tawhiri-datasets:/srv/tawhiri-datasets/
            - /Users/cheesiang_leow/sel_program/ruaumoko-dataset:/srv/ruaumoko-dataset/
        environment:
            - TZ=Asia/Tokyo

# volumes:
#     app-db-data: