# FROM tiangolo/uvicorn-gunicorn-fastapi:python3.7
FROM python:3.7
# FROM ubuntu

ENV DEBIAN_FRONTEND=noninteractive

# RUN apt-get update && apt-get -y upgrade
RUN apt-get update && apt-get -y upgrade
RUN apt-get -y install curl git wget tzdata python3 python3-pip opam ocaml && \
    apt-get -y install build-essential rsync git libpcre3-dev libncurses-dev pkg-config m4 unzip aspcud autoconf bubblewrap && \
    apt-get -y install libssl-dev libgmp-dev libffi-dev libeccodes-dev libcurl4-gnutls-dev
RUN ln -sf /usr/share/zoneinfo/Asia/Tokyo /etc/localtime

WORKDIR /app/
COPY ./requirements.txt /app/
RUN pip3 install -r requirements.txt

COPY ./app /app
ENV PYTHONPATH=/app
RUN python build_cython.py build_ext --inplace

CMD ["uvicorn", "main:app", "--reload", "--host", "0.0.0.0", "--port", "8000"]
